site_name: Tridentu Wiki
nav:
   - Home: index.md
   - About: about.md
theme:
     name: terminal
     features:
       - footer.prev_next
       - revision.date
       - revision.history
       - content.code.copy
plugins:
  search: {
    lang: en
  }
  git-revision-date: {}
  extract_listings: {
     listings_file: "search.md",
     javascript_search_file: "listing-search.js",
     placeholder: PLACEHOLDER_LISTINGS_PLUGIN
  }
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
